## Uncomment and set this to only include directories you want to watch
# directories %w(app lib config test spec features) \
#  .select{|d| Dir.exist?(d) ? d : UI.warning("Directory #{d} does not exist")}

## Note: if you are using the `directories` clause above and you are not
## watching the project directory ('.'), then you will want to move
## the Guardfile to a watched dir and symlink it back, e.g.
#
#  $ mkdir config
#  $ mv Guardfile config/
#  $ ln -s config/Guardfile .
#
# and, you'll have to watch "config/Guardfile" instead of "Guardfile"

guard 'rake', :task => 'full_rebuild', :run_on_start => false, :run_on_all => true do
  watch 'anonymize'
  watch 'events_and_event_pages'
  watch 'load_meals'
  watch 'load_needs'
end

guard 'rake', :task => 'reload_ddocs', :run_on_start => false, :run_on_all => false do
    watch 'load_design_documents'
    watch %r{^design_documents/.+}
end

